name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:

env:
  DOTNET_INSTALL_DIR: "./.dotnet"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "8.0.x"
      - run: dotnet restore --verbosity quiet
      - run: dotnet format ouranos-foundry.sln --verify-no-changes

  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "8.0.x"
      - run: dotnet restore --verbosity quiet
      - run: dotnet build ouranos-foundry.sln --no-restore
