<Project Sdk="Godot.NET.Sdk/4.6.3">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>Ouranos.Foundry</RootNamespace>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Tests\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Include=".gitattributes" />
    <Content Include=".gitignore" />
    <Content Include="Automation\pre-commit" />
    <Content Include="Automation\pre-push" />
    <Content Include="project.godot" />
  </ItemGroup>

  <ItemGroup>
    <EditorConfigFiles Remove=".editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="OuranosFoundry.Tests" />
  </ItemGroup>

  <Target Name="CopyGitHooks" AfterTargets="AfterBuild">
    <ItemGroup>
      <_CustomFiles Include="./Automation/pre-commit" />
      <_CustomFiles Include="./Automation/pre-push" />
    </ItemGroup>
    <Copy SourceFiles="@(_CustomFiles)" DestinationFolder="./.git/hooks" />
  </Target>
</Project>
