name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:

env:
  DOTNET_INSTALL_DIR: "./.dotnet"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-dotnet@v6
        with:
          dotnet-version: "10.0.x"
      - run: dotnet restore --verbosity quiet
      - run: dotnet tool restore --verbosity quiet
      - run: dotnet csharpier check .
      - run: dotnet format style --no-restore OuranosFoundry.sln --verify-no-changes
      - run: dotnet format analyzers --no-restore OuranosFoundry.sln --verify-no-changes

  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-dotnet@v6
        with:
          dotnet-version: "10.0.x"
      - run: dotnet restore --verbosity quiet
      - run: dotnet build OuranosFoundry.sln --no-restore
